[toolchain]
anchor_version = "0.32.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pledge = "68c1eNdHAfNWJhCWhtqumiqzYyFcDNLkfgwKwdFwFRcd"

[programs.devnet]
pledge = "68c1eNdHAfNWJhCWhtqumiqzYyFcDNLkfgwKwdFwFRcd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../keys/deployer.json"

[scripts]
test = "echo 'integration test runs against devnet: node ../scripts/e2e-devnet.mjs'"
